# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/thomasshih/Desktop/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition.xci
# IP: The module: 'AudioPosition' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thomasshih/Desktop/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioPosition'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/thomasshih/Desktop/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition.xci
# IP: The module: 'AudioPosition' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/thomasshih/Desktop/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioPosition'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
