# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.cache/wt} [current_project]
set_property parent.project_path {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.xpr} [current_project]
set_property XPM_LIBRARIES XPM_CDC [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo {e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.cache/ip} [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_mem {
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/ROM_data.txt}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/ROM_data1.txt}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/data_hour.txt}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/month_decoder.mem}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/calendar.txt}
}
read_verilog -library xil_defaultlib {
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/divider.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/loaderr.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/numberh2.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/numberh1.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/decoder.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/clockdivider.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/hour_divider.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/number1.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/number.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/LUT.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/minute_enabler.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/divider_1Hz.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/debouncer.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/pm_driver.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/mux_driver.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/laoder_f.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/big_mux.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/top.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/topper.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/comparator.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/alarm.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/alarm_setflash.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/time_zone.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/day_enabler.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/cal_incrementer.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/month_enabler.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/day_reset.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/month_fixer.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/month_decoder.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/LUT_cal.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/LUT_cal2.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/LSFR.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/WM_timer.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/WM_SM.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/new/WM_counter1.v}
  {E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/imports/new/AudioTest.v}
}
read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_0/c_counter_binary_0_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_1/c_counter_binary_1_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/c_counter_binary_2/c_counter_binary_2_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/month_counter/month_counter.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/month_counter/month_counter_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioPosition/AudioPosition_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc}}]
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc}}]

read_ip -quiet {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine.xci}}
set_property used_in_implementation false [get_files -all {{e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine_ooc.xdc}}]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/constrs_1/imports/lab9_3_3/Nexys4DDR_Master.xdc}}
set_property used_in_implementation false [get_files {{E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/constrs_1/imports/lab9_3_3/Nexys4DDR_Master.xdc}}]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top topper -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef topper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file topper_utilization_synth.rpt -pb topper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
