# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/tshih/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine.xci
# IP: The module: 'AudioLine' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tshih/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioLine'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/tshih/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine.xci
# IP: The module: 'AudioLine' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/tshih/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/AudioLine/AudioLine_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'AudioLine'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
