# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: E:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xci
# IP: The module: 'clk_wiz_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: e:/Onedrive/OneDrive - Carleton University/Assignments-Labs/ELEC 3500/alarm_clock_competition/alarm_clock_competition.srcs/sources_1/ip/clk_wiz_0_1/clk_wiz_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clk_wiz_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
